### ISSUE TITLE
Respin Debian build deb not available

### ISSUE THREAD

**Issue by anantshri** [ch1x0r/LinuxRespin#1]
https://github.com/ch1x0r/LinuxRespin/blob/master/debian/respin-deb_1.0.0-1_all.deb

**Comment by ch1x0r** [comment]
that  is true

**Comment by anantshri** [comment]
So are we fixes that or do you want us to build it from source.

**Comment by ch1x0r** [comment]
recently, I came to the understanding the ubuntu and mint were not working so these were the focus. Definitely will focus on Debian but the tester is unavailable and this will take some time. Maybe 1 week. Otherwise, yea...  build from the source should work.
