### ISSUE TITLE
The Ubuntu docx file isn't the correct file

### ISSUE THREAD

**Issue by KennXion** [ch1x0r/LinuxRespin#13]
I'm trying to figure out how to do the configurations for respin and the file Draft1-Ubuntu_0226.docx is actually the same file as the Yocto one...  If  you could just upload something that gives the respin parameters and how to configure its various options that would be great!

**Comment by ch1x0r** [comment]
This really isn't the Ubuntu repo. That is found on Launchpad. See chamuco linuxrespin on launchpad for the Ubuntu files. But thanks!!!  Did not know

**Comment by ch1x0r** [comment]
This really isn't the Ubuntu repo. That is found on Launchpad. See chamuco linuxrespin on launchpad for the Ubuntu files. But thanks!!!  Did not know
