### ISSUE TITLE
Backup results in a NW.js locked error

### ISSUE THREAD

**Issue by KennXion** [ch1x0r/LinuxRespin#14]
Whenever I boot from the USB flash-based disk created from a respin backup I get a Profile Locked NW.js  error that I have to click through on each boot to unlock the profile.  Is this normal behavior for the Backup?

**Comment by KennXion** [comment]
Bump.

**Comment by KennXion** [comment]
Bump Again....

**Comment by ch1x0r** [comment]
Which base? I just uploaded a few Ubuntu files if you are using Ubuntu. These actually come from chamuco's repo on launchpad. He is the Ubuntu lead.
