### ISSUE TITLE
Can respin make a live cd installer?

### ISSUE THREAD

**Issue by colesdev** [ch1x0r/LinuxRespin#15]
I manage to make a live cd for debian jessie but can respin make a live cd installer? like the old remastersys.   I have install tons of dependency in the new installation in the system and I dont to reinstall it back so need to make a live cd installer. Thanks. Sorry for my bad english

**Comment by miserable-old-git** [comment]
@colesdev Does [this](https://github.com/ch1x0r/LinuxRespin/issues/18) work for you?
