### ISSUE TITLE
custom-dist.iso not booting 

### ISSUE THREAD

**Issue by Nedihardt97** [ch1x0r/LinuxRespin#17]
So I've been working on some custom distros for a few weeks, but every time I try to boot off one I make with respin, it won't boot.
I am running Ubuntu 16.04 64 bit with all the repsin dependencies installed.
I have tried both VM and live usb via the startup disk creator, and both fail exactly the same.
Does anyone know what I'm doing wrong?
![virtualbox_amadeus-test_02_02_2017_09_32_57](https://cloud.githubusercontent.com/assets/25507769/22553486/dd6ca6ea-e92a-11e6-946c-2b6cdcfdeb44.png)

**Comment by KennXion** [comment]
I've been having success with using Unetbootin to create the boot disk from the ISO file.  Not sure if this would help but it might be worth a try.  It's free and runs on Win/Mac/Lin.  I've been writing the ISO from a Win 10 box.

**Comment by Nedihardt97** [comment]
would you happen to know whether or not it uses a FAT filesystem or a FAT32 one?

**Comment by KennXion** [comment]
FAT32. I usually do a full (not quick) Format in FAT32 and then load up the custom ISO and load it on the drive.

**Comment by Nedihardt97** [comment]
Ok, that's what I thought. I read up on people who were having that error output for general installs, and they said using FAT (16) instead of FAT 32 fixed it.
I'll be sure to try your methodology before attempting FAT (16) though. 
Thanks for the info!

**Comment by Nedihardt97** [comment]
Also, could you tell me what distro you tell Unetbootin your custom iso is?

**Comment by KennXion** [comment]
You don't have to pick anything up top. That's only if you want it to download a distro. Just pick the ISO down below and you should be fine. I was confused by that at first too.

**Comment by Nedihardt97** [comment]
Awesome! Worked perfectly!
While I'm here, would you happen to know any good tutorials on customizing the OS such as setting default startup programs and usernames?
Thanks for the help!

**Comment by KennXion** [comment]
Glad that worked.  I've tried to get help on here but the project seems to be ignored for the most part.  I have 2 issues that haven't been addressed myself despite emailing the author.  Anyway, I've been looking for that sort of thing as well but haven't really found a good source.  There used to be a project called uck (Ubuntu Customization Kit) that doesn't appear to be supported either and I think they may have some manual instructions that might be useful but I haven't gone through them yet.

**Comment by Nedihardt97** [comment]
I tried uck, but I didn't like it too much.
Right now, I'm trying out Pinguy since it seems like it will be more reliable than LinuxRespin.

**Comment by KennXion** [comment]
I looked at Pinguy but its author has stated that it's no longer supported at all, whereas LinuxRespin will work with currently supported Distros. My hope is that the author will not let this project fall completely by the wayside. That would be a shame.  Good luck, though!
