### ISSUE TITLE
Respin installation on Ubuntu 16.04 failes

### ISSUE THREAD

**Issue by jamrizzi** [ch1x0r/LinuxRespin#2]
The reason for this is because the xresprobe package is not available.  I was able to get it installed and working on Ubuntu 16.04 by running the following list of commands.

```
wget http://security.ubuntu.com/ubuntu/pool/universe/x/xresprobe/xresprobe_0.4.24ubuntu9_amd64.deb
dpkg -i xresprobe_*ubuntu9_amd64.deb
apt-get install -y dialog casper libdebian-installer4 ubiquity-frontend-debconf user-setup discover
apt-get -fy install
git clone https://github.com/ch1x0r/LinuxRespin.git
dpkg -i LinuxRespin/ubuntu/respin_1.1.0-1_all.deb
```

**Comment by ch1x0r** [comment]
Great! Thanks!
Here is a link to the PPA and packages for the Ubuntu team. They updated to 16.04.
https://launchpad.net/~sergiomejia666/+archive/ubuntu/respin/+packages

**Comment by fredbcode** [comment]
Respin works with Ubuntu 16.04 ? It can generates a full running iso ?

**Comment by fredbcode** [comment]
Oh good, I didn't see any significant differences with respin and pinguybuilder, or remastersys, and the both are buggy with 16.04
Thanks, I will make a test

**Comment by ch1x0r** [comment]
So, respin is a fork of remastersys. We did get the original code from Tony who was the lead dev for that project. Remastersys was abandoned way before 16.04...

**Comment by frieding** [comment]
I like respin. But all my trials end up at now with an .iso file of 36K, even the live-system has 12GB. Any idea for help?
I'm using ubuntu 16.04, running on an USB-Stick of 16GB which i'd like to clone to a live-System for distribution.

frieding

**Comment by frieding** [comment]
I found the reason for the behaviour of generationg only a 36K iso-file. It's very simple: You have to install isolinux!  Thus is a the preresquisite for making mkisofs!

"sudo apt-get install isolinux"

Regards
frieding

**Comment by bytus** [comment]
HELP ...

dpkg-deb: error: `respin-deb_1.0.0-1_all.deb' no es un archivo en formato debian
dpkg: error al procesar el archivo respin-deb_1.0.0-1_all.deb (--install):
 el subproceso dpkg-deb --control devolvió el código de salida de error 2
Se encontraron errores al procesar:
 respin-deb_1.0.0-1_all.deb

**Comment by bytus** [comment]
Procesando disparadores para menu (2.1.46) ...
/usr/share/menu/respin: 1: /usr/share/menu/respin: Syntax error: word unexpected (expecting ")")
Se encontraron errores al procesar:
