### ISSUE TITLE
Wrong size 

### ISSUE THREAD

**Issue by cerberus333** [ch1x0r/LinuxRespin#24]
I use respin ( fork remastersys ) to remaster my os. installer os = 1gb. After install, sdb1 = 2 gb. myremaster = 1 gb. My question, after install myremaster use respin-installer. Why my sda1 = 5gb?. it's bigger then sdb1.
( i only add tool respin and mousepad before remaster ). Sorry for my english.

**Comment by ch1x0r** [comment]
Interesting! Which is is the base can I ask? Not that it matters but I am not Ubuntu. So I can get the right repo to you.

**Comment by cerberus333** [comment]
I am use kalilinux rolling 2016.2 base debian

**Comment by ch1x0r** [comment]
is your drive encrypted?

**Comment by cerberus333** [comment]
my drive not encrypt. Ok ....  ^_^

**Comment by cerberus333** [comment]
Thanks
