### ISSUE TITLE
Using it to backup running system

### ISSUE THREAD

**Issue by Nixellion** [ch1x0r/LinuxRespin#26]
Hello,

I'm not sure if this tool is what I am looking for, could anyone, please, comment on this?
I have a home server, it runs off SSD, and I want to make regular backups of the entire system image, so that, in case of SSD Failure I would be able to just take another SSD, and restore the entire image of the drive there.

Can Respin be used for this? If not, are there any other tools that can do that? Without pulling the SSD out and using a separate machine to make said copy.

Thanks.

**Comment by Lew-Rockwell-Fan** [comment]
Tony always used to categorically say shut down all other programs while making a backup. Technically this IS run from a running system, but if you follow his dictum,  ideally it should be a running system that isn't DOING anything. Having said that, I know you can get away with running some things. I pretty regularly read an epub while the backup  is running. Hasn't seemed to cause problems. I suspect that once this starts to make the iso, the main issue at that point is merely resource usage, but i might be wrong. Obviously, there are limits. Trying to backup a system that is changing could result in something  unusable. You don't say what you are running. This is specifically for OSs in the Debian family including the 'buntus and Mints and so on. If you are running something else, and ALL you are doing is backing up  and don't care about a live disk, you might look at fsarchiver. But backing up the running system while it is actually doing something is considered risky and not really recommended although they do have an option for that. Use at your own risk.

**Comment by ch1x0r** [comment]
I am contacting another dev. He uses SSD. Will respond back soon... I hope.

**Comment by ch1x0r** [comment]
Nixellion, 

He said the ssd shouldn't matter. If you are using a Deb based system - give it a try. If you have any issues... let me know!
