### ISSUE TITLE
How to contrib to wiki or suggest code?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [ch1x0r/LinuxRespin#31]
When I click on Wiki I get the code page. Am I doing it wrong? I was going to post something there but I posted it as an "issue" instead since I couldn't get the Wiki to work.

Also, when and if I have suggestions for modifications to the main Respin script, how do I submit them?

**Comment by ch1x0r** [comment]
<img width="706" alt="screen shot 2017-06-16 at 3 37 06 am" src="https://user-images.githubusercontent.com/4945600/27223414-2b8f71b2-5245-11e7-9cbe-8cca5284bf13.png">

**Comment by ch1x0r** [comment]
it was set but I never created a page... just did

**Comment by Lew-Rockwell-Fan** [comment]
Thank you. Color me stupid. I've looked all over those 2 pages, Home, and Welcome. I've turned my Pale Moon Night Mode off an on. I even tried selecting all on the page. If I click on "1 revison" a new page bbutton appears. But if I click it, it just takes me back to the Home page. I don't even see anything like an edit button. Maybe I'll try with another browser.

**Comment by ch1x0r** [comment]
Dude... you use Pale Moon - who are you!!!! Maybe start a page? Let me
see...

**Comment by ch1x0r** [comment]
<img width="1045" alt="screen shot 2017-06-16 at 6 45 17 pm" src="https://user-images.githubusercontent.com/4945600/27249185-091a1e14-52c4-11e7-8749-3f154bda7477.png">

Also - all the team is meeting tomorrow to unveil / test / discuss your gui... 
We have one but you said Uninstaller....
So, I haven't looked at it yet as I promised we could all look at it together.

Can't wait to see the code!

**Comment by ch1x0r** [comment]
OMG... wait. You're at the command line? are you BEHIND the Command Line! Can you see the image I posted?

**Comment by Lew-Rockwell-Fan** [comment]
Thank you. Hey, that GUI isn't much. Pretty crude really. I haven't studied how to make  debs or mark dependencies. It will leave the package "gxmessage", which is like zenity, behind. I thought about testing for it's presence and keeping a record and uninstalling it if it wasn't there to begin with, but, that would really PO somebody who had started using it in their own scripts in the mean time, so I left well enough alone. Gtk-dialog is better for that sort of thing, albeit a lot harder to write with, but gxmessage is in the Xenial repo and gtk-dialog isn't.

Re your image. Yes, I can see it.  It isn't what I see. I may try clicking blind in the white area, based on your image. But shouldn't I get SOME sort of blank page when I click the new-page button if it just a visual/colors kind of issue? If I click an invisible  edit button, on a "new page" that looks just like the "Home page" I  may wind up replacing  the Home by accident,  or maybe the default new page is a copy of Home? That'd be a nutty way for Github to do it. Hmmm. Lemme look at my popup and script settings. Maybe that's got something  to do with it. Obviously the link works for you because you made a second page. Maybe the PM version of https-everywhere is messing with it. I'll try fooling with some of those things.
