### ISSUE TITLE
Can we use respin to create distributable iso image of Ubuntu server 16.04 or 14.04

### ISSUE THREAD

**Issue by masifpak** [ch1x0r/LinuxRespin#33]
I need to create an iso image ubuntu 14.04 and ubuntu 16.04 with installed my packages and setup. I am facing some problem in rsync permission denied. Please guide me some steps. Please have a look on below link.
https://pastebin.com/9MYK648U

**Comment by ch1x0r** [comment]
This is actually the Debian version. The Ubuntu version is hosted at launchpad or whatever that deal is over there at Ubuntu.
Uh... I don't understand what you mean by that title. I'm closing this issue. Server is irrelevant. You can spin your server dude... Why would you use ubuntu for a server anyway. LOL

**Comment by ch1x0r** [comment]
In other words - check your permissions - everywhere. If that doesn't work - well, ask Chamuco over at launchpad or on github.

This is the Debian version. There is good Ubuntu support for Ubuntu

**Comment by masifpak** [comment]
I am not using Ubuntu desktop as server. I am using Ubuntu server flavor.

**Comment by ch1x0r** [comment]
I understand. I don't think you do. 
This is the Debian offering. this is why ughbuntu stuff is on here:
https://github.com/ch1x0r/LinuxRespin/wiki/This-is-not-The-Ubuntu-Version

**Comment by ch1x0r** [comment]
Here's the answer: If you are using Ubuntu as a desktop or a server -  you need to consider a few things.. Did you use flouride as a child? do you like excitotoxins? Should you go back to using some totally proprietary system? Look at the facts dude. They can't even deliver on product to companies that actually would pay them. LMAO. http://linuxbsdos.com/2013/03/08/ubuntu-is-not-a-community-distribution/ . F*** UBUNTU

**Comment by masifpak** [comment]
Thanks for the time. What if we deploy debian without Desktop, even then respin would work properly?

**Comment by muzzol** [comment]
I'm amazed about the many rude comments here.

I also use ubuntu server ISO as the base of my custom desktop system because alternate version was dropped some time ago and desktop version is not as customizable as that one.

I also use ubuntu as server a lot, your patronization only makes you look arrogant and ignorant.

_booya_

**Comment by muad-dweeb** [comment]
Seriously @muzzol. I'm kind of peeved that the developer here is belittling a user and trash-talking Ubuntu. What does that solve?

**Comment by ch1x0r** [comment]
u·bun·tu
ˌo͝oˈbo͝on(t)o͞o/Submit
noun
I cannot configure Debian
