### ISSUE TITLE
Dependency not satisfable: casper

### ISSUE THREAD

**Issue by diesater** [ch1x0r/LinuxRespin#34]
Hello, i'm trying to install respin on debian 9, testing repos abilitated.
The problem is that i can't install respin.
I get "Dependency not satisfable: casper" error.
So far i tried:

> apt-get update
> apt-get upgrade
> apt-get install respin.deb in the downloaded folder
> apt-get install -f respin.deb
> apt-get install -f
> gdebi
> enabling i386 architecture

I tried every .deb installation file present in github.
Nothing worked so far.

Screenshots:

![virtualbox_debian_28_06_2017_21_45_32](https://user-images.githubusercontent.com/19558112/27657480-170e1a56-5c4d-11e7-9745-42801e883443.png)
![virtualbox_debian_28_06_2017_21_45_53](https://user-images.githubusercontent.com/19558112/27657479-170d0ad0-5c4d-11e7-9025-0c8eac47cf3a.png)

**Comment by ch1x0r** [comment]
so, you are on stretch. Very cool. Systemd... right?
Ok, let me see if I have some time this holiday weekend to work on a rev. Not sure how it will go. No promises. So the simplest answer would be... find a casper pkg... but not sure if it will work with other dependencies. Ohhh. I get to install STRETCH! will get back to you.

**Comment by diesater** [comment]
i've tried downloading casper, resolving manually all the dependecies, it fails to install ubiquity.
i forgot to tell that i'm using debian testing repositories, if that's important.
thank you anyway.

**Comment by ch1x0r** [comment]
You can comment out the ubiquity line...But if it's asking for ubiquity
then you probably are using the Ubuntu version. Try the Debian.

**Comment by diesater** [comment]
Well, ubiquity is asked from casper, because i had to download casper.deb from a ubuntu repository.
casper is no longer avaible in debian's official repos
