### ISSUE TITLE
Announcement - No longer supporting Ubuntu Users - Debian ONLY

### ISSUE THREAD

**Issue by ch1x0r** [ch1x0r/LinuxRespin#36]
Thanks to the persistent and unacceptable requests from Ubuntu (l)users, I will no longer be supporting the Ughbuntu version here.

If you want to find the github and the launchpad, please use duckduckgo, Google or some search engine.

Thank you. I tried supporting the users, but the questions were absolutely ridiculous and not an effective use of time.

**Comment by LissieTilbrook** [comment]
I'm sorry... but I don't understand why you want to do this? If you want to tell me why... I might as well fork this if you don't want to support Ubuntu users... like me.

**Comment by LissieTilbrook** [comment]
Forked. https://github.com/LissieTilbrook/WickedRespin

Ubuntu users, WHOOP WHOOP!
