### ISSUE TITLE
How Much Do You Care?

### ISSUE THREAD

**Issue by opticyclic** [ch1x0r/LinuxRespin#38]
`Sentence use: I could care less about community`

So how much do you care? ;)
https://www.youtube.com/watch?v=om7O0MFkmpw

**Comment by ch1x0r** [comment]
Great point. We are a global community.

LOL. Should have used simplified English! Especially ... for those Ubuntu Users.

**Comment by LissieTilbrook** [comment]
Okay, you hate Ubuntu users. I get it.

But please, stop the hate.

**Comment by ch1x0r** [comment]
There is already an Ughbuntu release - maintained and updated by chamuco on the Ughbuntu Launchpad. You did nothing.
