### ISSUE TITLE
Double naming of Debian on the Homepage

### ISSUE THREAD

**Issue by ShalokShalom** [ch1x0r/LinuxRespin#39]
![screenshot_20170918_224653](https://user-images.githubusercontent.com/6344099/30563907-9b129168-9cc3-11e7-880d-6f56a36f0188.png)

See yourself, Debian is mentioned next to Mint and above.

**Comment by ShalokShalom** [comment]
So, Mint is not supported anymore?

I see still a .deb here: https://github.com/ch1x0r/LinuxRespin/blob/master/respin-mint_1.1.0-1_all.deb

**Comment by ch1x0r** [comment]
Right now I'm working on Trisquel - I have it working just have to test the ISO

**Comment by ShalokShalom** [comment]
Oh fine, thanks. :smile:
