### ISSUE TITLE
Win32 loader support

### ISSUE THREAD

**Issue by ShalokShalom** [ch1x0r/LinuxRespin#40]
The Win32 loader provides a support, in order to install Debian without any live media and also without any need to access the UEFI/BIOS.

This is especially helpful for people, who struggle with such technical details.

https://people.debian.org/~rmh/goodbye-microsoft/

Thanks a lot in advance; Matthias. ;-)

**Comment by ch1x0r** [comment]
What is the relevance to building a distro or backups?

**Comment by ch1x0r** [comment]
Win anything smh...try an SD card install...smh

**Comment by ShalokShalom** [comment]
Its about building a Distro with this Installer. I like to create a distro for quite old people and other casual users with less experience. With this tool get the whole process more easy. Its simply simpler. ;)

**Comment by ch1x0r** [comment]
Actually, that is good, but can you fork it and take out the Win... for the win!? :D

**Comment by ShalokShalom** [comment]
https://packages.debian.org/de/source/sid/win32-loader
