### ISSUE TITLE
"Recursive Partition

### ISSUE THREAD

**Issue by GlenHenshaw** [ch1x0r/LinuxRespin#44]
Not sure whether I'm just screwing this up, but when I dd (or cp) the custom ISO to a thumb drive, I can't boot from it. Looking at the drive in GParted gives the following error:

     "Invalid partition table - recursive partition on /dev/sdX"

**Comment by ch1x0r** [comment]
i create one last night - let me test it and get back to you.

**Comment by ch1x0r** [comment]
working on it!

![respindist1](https://user-images.githubusercontent.com/4945600/34227555-d051b63c-e58a-11e7-8085-11e3a5b7c612.png)
![respindist2](https://user-images.githubusercontent.com/4945600/34227556-d065ed28-e58a-11e7-947f-0a6d7ff62455.png)
![respindist3](https://user-images.githubusercontent.com/4945600/34227557-d078774a-e58a-11e7-9214-319facf096b5.png)


![iso](https://user-images.githubusercontent.com/4945600/34227541-c39177c0-e58a-11e7-93d2-40a468ee308a.png)

**Comment by ch1x0r** [comment]
I should have read this earlier... my bad.

Pls share your dd command.

**Comment by ch1x0r** [comment]
oh... so it says "it is recommended to run 'sudo respin clean' once you have burned and tested the "Name of iso"

Maybe I can edit that to

psa:  ISO Samurai says run 'sudo respin clean' after you burned and tested the iso.
