### ISSUE TITLE
Is respin-mint_1.1.0-1_all.deb OK for D.9, Stretch?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [ch1x0r/LinuxRespin#45]
I'll probably just try it one way or the other soon if nobody wanders by and comments before I get to it, but I was hoping for some clarification of how I'm supposed to install this on Stretch. The name of the respin-mint_1.1.0-1_all.deb file sounds like it is specifically for Mint, but the only other debs I see are much older & look like they  might  be for Jessie. If I want to try this on Stretch, do I have to compile it or can I use one of the debs? Or is Stretch not supported at all?

The sys I want to try it on is NOT LMDE, but made from the standard 1-cd installer for Stretch (not the net-install, and not the DVD set, but the bigger of the 2 1-cd options). Also, are there hash values anywhere? Gpg sigs?

**Comment by ch1x0r** [comment]
It's been a while since I updated the software. Using makefile - yea. hash values are available.
Let me note that. I know Tony did use GPG sigsr but no, I never did.... yet?
