### ISSUE TITLE
crashed when installing

### ISSUE THREAD

**Issue by wordyallen** [ch1x0r/LinuxRespin#5]
While installing the custom.iso  the bootloader was no longer available. It just crashed.  

great work by the way!

**Comment by ch1x0r** [comment]
Hi, 
Were you using this with Debian as your base?
Thanks!

**Comment by wordyallen** [comment]
Ubuntu 14. Please let me know if you'd like a log

**Comment by ch1x0r** [comment]
Hi, Please send the log!

**Comment by ch1x0r** [comment]
please try the Ubuntu 14 located in the Ubuntu Directory folder. This version may need xresprobe installed.
