### ISSUE TITLE
Can't boot iso on Mac

### ISSUE THREAD

**Issue by 33masterman33** [ch1x0r/LinuxRespin#50]
I used respin on Debian 9 to create a backup ISO. I can write the iso to a flash drive and boot on a PC but it doesn't show up on mac I have tried using Rufus and Unetbootin. What should I do to be able to boot this live USB on boot Mac and PC?

**Comment by ch1x0r** [comment]
Good question. What Mac...ppc or Intel?

**Comment by 33masterman33** [comment]
I'm using an Intel Macbook pro 2016

**Comment by ch1x0r** [comment]
I have one! Let me test tonight

**Comment by 33masterman33** [comment]
Ok, thank you so much.

**Comment by 33masterman33** [comment]
Any luck so far? I believe the issue is that the iso doesn't have an EFI boot sector.

**Comment by ch1x0r** [comment]
Yes, This definitely seems like an EFI boot manager related issue.
"Apple’s made it difficult to boot non-Mac OS X operating systems off of USB drives. While you can connect an external CD/DVD drive to your Mac and boot from standard Linux live CDs and USBs, simply connecting a Linux live USB drive created by standard tools like Universal USB Installer and uNetbootin to a Mac won’t work."
https://www.howtogeek.com/213396/how-to-boot-a-linux-live-usb-drive-on-your-mac/

**Comment by 33masterman33** [comment]
Ok, so this took me a little while to do because I built the program myself so I didn't have to pay and while it works I still can't use my Linux because my Mac is the touch bar model and Debian doesn't have drivers by default so I will see what I can do. Thanks.

**Comment by ch1x0r** [comment]
Oh. Good info! Thanks.
