### ISSUE TITLE
Is ubuntu supported or not ?!

### ISSUE THREAD

**Issue by Deltacrypto** [ch1x0r/LinuxRespin#59]
you have mentioned on readme file that ubuntu is not supported so why there is a .deb for ubuntu ?! is ubuntu supported or not ? i wanna respin ubuntu 18.04 if its supported. thanks.

**Comment by pinguy** [comment]
ch1x0r has just copied Pinguy Builder and renamed it.
https://github.com/ch1x0r/LinuxRespin/commit/61dcabd16eaaa70ea29a98bfae03de7b4f03453a

I have updated Pinguy Builder to fully work with all *buntu 18.04 versions.
https://sourceforge.net/projects/pinguy-os/files/ISO_Builder/

**Comment by ch1x0r** [comment]
Isn't open source great! You have so many options. If his works on 18.04, that may be the best way to go until some of the Ubuntu community pitches in and tests. Seriously, I really am focusing on Buster right now and the NUC platform. I have a few NUC EFI solutions I posted but anyway - yea. There are a bunch of Ubuntu options out there.
