### ISSUE TITLE
cannot mount /dev/loop0 on //filesystem.squashfs

### ISSUE THREAD

**Issue by luskbo** [ch1x0r/LinuxRespin#6]
Ubuntu 14.04 failing to load after GRUB menu.
Was a regular remastersys user last year, first time respin user.
Never had this problem before.
Used the backup feature to build a USB Live disk.
ISO seems to build successfully. 
Use unetbootin and universal live disk creator to make disk.
Booting on legacy BIOS from USB.
After selecting to load live disk. getting this error:

(initramfs) mount: mounting /dev/loop0 on //filesystem.smashfs failed: Invalid argument
CAn not mount /dev/loop0 (/cdrom/casper/filesystem.squashfs) on //filesystem.squashfs

I have troubleshooted by using different USB, using different methods to write to 
USB, and also different PCs. Same issue in all circumstances. Any ideas?

**Comment by ch1x0r** [comment]
Here's my first pass at this.
Did you get any installation errors regarding dependencies - such as casper?

Possibly:
apt-get install --yes ubuntu-standard casper lupin-casper

For the ubuntu version, no functionality was modified for respin from remastersys.
If you go to Chamuco's launchpad - you can get modified and more recent respin packages for Ubuntu.

**Comment by luskbo** [comment]
No dependency issues, and yes casper is installed.
 casper and  ubiquity-casper

Going to try chamucos.

**Comment by luskbo** [comment]
Tried chamucos, and experienced the same issue. 
Going to try with a fresh install of Ubuntu 14.04 without any modifications first. 
Just FYI, I used the .deb package from your github first.

**Comment by ch1x0r** [comment]
Hm. are you using a VM?

**Comment by luskbo** [comment]
Okay, resolved the issue. Looks like it was the USB writing software I was using. I used dd to double check and that worked as it should. Thanks for responding.
