### ISSUE TITLE
xresprobe

### ISSUE THREAD

**Issue by tony-travis** [ch1x0r/LinuxRespin#8]
The Ubuntu .deb can't be installed under "Xenial" (16.04 LTS) because the "xresprobe" package is only available in "Precise" and "Trusty":

http://packages.ubuntu.com/search?keywords=xresprobe

lsb_release -d
Description:    Ubuntu 16.04.1 LTS

gdebi respin_1.1.0-1_all.deb
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: xresprobe

**Comment by ch1x0r** [comment]
Yes, the xresprobe package is not available. Try the following list of commands.

wget http://security.ubuntu.com/ubuntu/pool/universe/x/xresprobe/xresprobe_0.4.24ubuntu9_amd64.deb
dpkg -i xresprobe_*ubuntu9_amd64.deb
apt-get install -y dialog casper libdebian-installer4 ubiquity-frontend-debconf user-setup discover
apt-get -fy install
git clone https://github.com/ch1x0r/LinuxRespin.git
dpkg -i LinuxRespin/ubuntu/respin_1.1.0-1_all.deb

**Comment by ch1x0r** [comment]
Here is a link to the PPA and packages for the Ubuntu team. They updated to 16.04.
https://launchpad.net/~sergiomejia666/+archive/ubuntu/respin/+packages

**Comment by tony-travis** [comment]
Same problem with "xresprobe" in their .deb's dependencies:
https://launchpad.net/~sergiomejia666/+archive/ubuntu/respin/+files/respin_2.0.6-0-73~ubuntu16.04.1_amd64.deb

gdebi respin_2.0.6-0-73~ubuntu16.04.1_amd64.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: xresprobe

**Comment by tony-travis** [comment]
Installed OK after:

wget http://security.ubuntu.com/ubuntu/pool/universe/x/xresprobe/xresprobe_0.4.24ubuntu9_amd64.deb
gebi xresprobe_0.4.24ubuntu9_amd64.deb

Thx.

**Comment by ch1x0r** [comment]
Great! I'll let chamuco know. I think he had something in his repo also about it. https://launchpad.net/~sergiomejia666/+archive/ubuntu/xresprobe   but I am unsure if that is working. Let's go with the
wget http://security.ubuntu.com/ubuntu/pool/universe/x/xresprobe/xresprobe_0.4.24ubuntu9_amd64.deb
gebi xresprobe_0.4.24ubuntu9_amd64.deb

I'm not closing this out because others may use it for future reference.

**Comment by pepa65** [comment]
Also, the package isolinux is required, because isolinux.bin isn't present on an installed system.

**Comment by pepa65** [comment]
Also, the package isolinux is required, because isolinux.bin isn't present on an installed system.

**Comment by aaronfranke** [comment]
I want to report that this package is still missing in 16.04.1 Xenial Xerus

**Comment by ch1x0r** [comment]
Posted! Look in the ubuntu folder.
